/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author luizo
 */
public class CadastroClientes extends javax.swing.JFrame {

    /**
     * Creates new form CadastroClientes
     */
    public CadastroClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCadastronome = new javax.swing.JLabel();
        txtCadastronome = new javax.swing.JTextField();
        lblCadastrocpf = new javax.swing.JLabel();
        lblCadastrosexo = new javax.swing.JLabel();
        txtCadastrocpf = new javax.swing.JTextField();
        cbxCadastrosexo = new javax.swing.JComboBox<>();
        lblCadastroendereco = new javax.swing.JLabel();
        lblCadastrocidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCadastroendereco = new javax.swing.JTextArea();
        txtCadastrocidade = new javax.swing.JTextField();
        lblUF = new javax.swing.JLabel();
        cbxUF = new javax.swing.JComboBox<>();
        btnLimpar1 = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblCadastroclientes = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblBuscacpf = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnLimpar2 = new javax.swing.JButton();
        lblBuscarnome = new javax.swing.JLabel();
        txtBuscarsexo = new javax.swing.JTextField();
        lblBuscarsexo = new javax.swing.JLabel();
        txtBuscarnome = new javax.swing.JTextField();
        lblBuscarendereco = new javax.swing.JLabel();
        lblBuscarcidade = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBuscarendereco = new javax.swing.JTextArea();
        txtBuscarcidade = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        lblBusca = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCadastronome.setText("Nome");
        jPanel1.add(lblCadastronome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));
        jPanel1.add(txtCadastronome, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 280, -1));

        lblCadastrocpf.setText("CPF");
        jPanel1.add(lblCadastrocpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        lblCadastrosexo.setText("Sexo");
        jPanel1.add(lblCadastrosexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        jPanel1.add(txtCadastrocpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        cbxCadastrosexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino", " " }));
        cbxCadastrosexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCadastrosexoActionPerformed(evt);
            }
        });
        jPanel1.add(cbxCadastrosexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 130, -1));

        lblCadastroendereco.setText("Endereço");
        jPanel1.add(lblCadastroendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        lblCadastrocidade.setText("Cidade");
        jPanel1.add(lblCadastrocidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        txtCadastroendereco.setColumns(20);
        txtCadastroendereco.setRows(5);
        jScrollPane1.setViewportView(txtCadastroendereco);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 280, -1));

        txtCadastrocidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadastrocidadeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCadastrocidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 120, -1));

        lblUF.setText("UF");
        jPanel1.add(lblUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, -1));

        cbxUF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO", "DF" }));
        cbxUF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxUFActionPerformed(evt);
            }
        });
        jPanel1.add(cbxUF, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        btnLimpar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnLimpar1.setText("Limpar");
        jPanel1.add(btnLimpar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 350, 100, 40));

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mole.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        jPanel1.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 100, 40));

        jLabel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(204, 204, 204))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 280, 80));

        lblCadastroclientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro de clientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(lblCadastroclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 350, 420));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBuscacpf.setText("CPF");
        jPanel2.add(lblBuscacpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/binoculars.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));

        btnLimpar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/limpar-limpo.png"))); // NOI18N
        btnLimpar2.setText("Limpar");
        jPanel2.add(btnLimpar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        lblBuscarnome.setText("Nome");
        jPanel2.add(lblBuscarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));
        jPanel2.add(txtBuscarsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 280, -1));

        lblBuscarsexo.setText("Sexo");
        jPanel2.add(lblBuscarsexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        jPanel2.add(txtBuscarnome, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 280, -1));

        lblBuscarendereco.setText("Endereço");
        jPanel2.add(lblBuscarendereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 60, 30));

        lblBuscarcidade.setText("Cidade");
        jPanel2.add(lblBuscarcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        txtBuscarendereco.setColumns(20);
        txtBuscarendereco.setRows(5);
        jScrollPane2.setViewportView(txtBuscarendereco);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, -1));

        txtBuscarcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarcidadeActionPerformed(evt);
            }
        });
        jPanel2.add(txtBuscarcidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 120, -1));

        lblEstado.setText("Estado");
        jPanel2.add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));
        jPanel2.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 130, -1));

        btnAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/updated.png"))); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 120, -1));

        btnDeletar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDeletar.setText("Deletar");
        jPanel2.add(btnDeletar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, -1));

        lblBusca.setBorder(javax.swing.BorderFactory.createTitledBorder("Busca de Clientes"));
        jPanel2.add(lblBusca, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, -4, 370, 420));

        jLabel11.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 330, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxCadastrosexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCadastrosexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxCadastrosexoActionPerformed

    private void txtCadastrocidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadastrocidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadastrocidadeActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtBuscarcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarcidadeActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void cbxUFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxUFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxUFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnLimpar1;
    private javax.swing.JButton btnLimpar2;
    private javax.swing.JComboBox<String> cbxCadastrosexo;
    private javax.swing.JComboBox<String> cbxUF;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBusca;
    private javax.swing.JLabel lblBuscacpf;
    private javax.swing.JLabel lblBuscarcidade;
    private javax.swing.JLabel lblBuscarendereco;
    private javax.swing.JLabel lblBuscarnome;
    private javax.swing.JLabel lblBuscarsexo;
    private javax.swing.JLabel lblCadastrocidade;
    private javax.swing.JLabel lblCadastroclientes;
    private javax.swing.JLabel lblCadastrocpf;
    private javax.swing.JLabel lblCadastroendereco;
    private javax.swing.JLabel lblCadastronome;
    private javax.swing.JLabel lblCadastrosexo;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblUF;
    private javax.swing.JTextField txtBuscarcidade;
    private javax.swing.JTextArea txtBuscarendereco;
    private javax.swing.JTextField txtBuscarnome;
    private javax.swing.JTextField txtBuscarsexo;
    private javax.swing.JTextField txtCadastrocidade;
    private javax.swing.JTextField txtCadastrocpf;
    private javax.swing.JTextArea txtCadastroendereco;
    private javax.swing.JTextField txtCadastronome;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
